name: Deploy Office_Save to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build JAR file
      run: |
        mvn clean package -DskipTests

    - name: Set up Docker permissions
      run: |
        sudo chmod 666 /var/run/docker.sock

    - name: Build Docker Image
      run: |
        docker build -t business-list-find:latest .
        sudo docker save business-list-find:latest > business-list-find.tar
        sudo chmod 644 business-list-find.tar

    - name: Transfer Docker Image
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.BUSINESS_EC2_HOST }}  # SECRETO PARA BUSINESS
        username: ec2-user
        key: ${{ secrets.BUSINESS_EC2_SSH_KEY }}  # SECRETO PARA BUSINESS
        source: business-list-find.tar
        target: /home/ec2-user/

    - name: SSH to EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.BUSINESS_EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.BUSINESS_EC2_SSH_KEY }}
        script: |
          sudo docker load < /home/ec2-user/business-list-find.tar
          sudo docker stop business-list-find || true
          sudo docker rm business-list-find || true
          sudo docker run -d -p 8081:8081 --name business-list-find business-list-find:latest
          rm /home/ec2-user/business-list-find.tar
